# Generated by Django 3.1.4 on 2020-12-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('O', 'Others'), ('M', 'Male')], max_length=100)),
                ('joiningdate', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('confirmpass', models.CharField(max_length=100)),
            ],
        ),
    ]
