# Generated by Django 3.1.4 on 2020-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.IntegerField()),
                ('loginpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reg_table',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'Others'), ('F', 'Female')], max_length=100),
        ),
    ]
