# Generated by Django 3.1.4 on 2020-12-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3app', '0002_auto_20201222_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_table',
            name='loginid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reg_table',
            name='gender',
            field=models.CharField(choices=[('O', 'Others'), ('F', 'Female'), ('M', 'Male')], max_length=100),
        ),
    ]
