# Generated by Django 3.1.4 on 2020-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3app', '0003_auto_20201223_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('confirmpass', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reg_table',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'Others'), ('F', 'Female')], max_length=100),
        ),
    ]
